### PR TITLE
Add a long description to PIP package page

### PR DESCRIPTION
**Pull request by ligurio**
For PIP project it is possible to show a detailed description of the
package. This is shown on the package detail page on the Python Package
Index [1]. Patch allows showing a long description loaded from
README.md, which is a common pattern [2].

1. https://pypi.org/project/mkrepo/
2. https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata

### CODE REVIEW

**Comment by ligurio** [comment]
@knazarov could you review?

**Review by Totktonada — APPROVED** [review]
I'm not an expert here, but it looks worthful to have. I'll take responsibility to merge it.

**Comment by Totktonada** [comment]
Oops, CI tells me the following:

```
isort . -c
ERROR: /home/runner/work/mkrepo/mkrepo/setup.py Imports are incorrectly sorted and/or formatted.
Skipped 1 files
make: *** [Makefile:13: isort] Error 1
```

I'll wait for a fix.

**Comment by ligurio** [comment]
@Totktonada, fixed:

```diff
--- a/setup.py
+++ b/setup.py                                                              
@@ -1,7 +1,8 @@                                                                                                                                         
 #!/usr/bin/env python
-from distutils.core import setup
                             
+from distutils.core import setup
 from os import path
+                
 this_directory = path.abspath(path.dirname(__file__))
 with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
     long_description = f.read() 
```

**Comment by Totktonada** [comment]
Thanks!

**Comment by Totktonada** [comment]
NB: It'll show its effect on https://pypi.org/project/mkrepo/ at next release.

PyPI does not allow to re-deploy existing releases. I don't see any other way to update the description.

**Pull request merged**
